# Generated by Django 6.0.6 on 2026-07-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('tracking_id', models.PositiveBigIntegerField(help_text='شناسه یکتای هر اطلاعیه در سامانه کدال', primary_key=True, serialize=False, verbose_name='شناسه رهگیری کدال')),
                ('symbol', models.CharField(db_index=True, help_text='نام نماد بورسی (مثلاً فولاد)', max_length=100, verbose_name='نماد')),
                ('title', models.CharField(help_text='عنوان کامل اطلاعیه', max_length=500, verbose_name='عنوان اطلاعیه')),
                ('publish_date', models.DateTimeField(help_text='تاریخ و ساعت انتشار اطلاعیه', verbose_name='تاریخ انتشار')),
                ('direct_link', models.URLField(help_text='لینک مستقیم به صفحه گزارش در سایت کدال', max_length=1000, verbose_name='لینک مستقیم')),
                ('letter_code', models.CharField(blank=True, default='', help_text='کد نوع نامه/گزارش', max_length=50, verbose_name='کد نامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در دیتابیس')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['symbol', '-publish_date'], name='idx_symbol_publish_date')],
            },
        ),
    ]
