# Generated by Django 6.0.6 on 2026-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ و ساعت انتشار اطلاعیه', null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
