# Generated by Django 6.0.6 on 2026-07-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_announcement_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='نماد')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('sector', models.CharField(max_length=100, verbose_name='صنعت')),
                ('sector_icon', models.CharField(default='📊', max_length=10, verbose_name='آیکون صنعت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
    ]
